/**
 * The CSV download.
 *
 * The file is generated by `card.series.to_csv` inside Pyodide — the same
 * function behind `card series` — so what a reader downloads here is
 * byte-identical to what they would get from the CLI. That is why this needs
 * the live model and cannot be served from the precomputed layer: those values
 * are interpolated, and a file that silently mixed exact and approximate rows
 * would be worse than no file.
 *
 * So the button may start the 5.8 MB download, and says so before it does.
 */

import { useCallback, useState } from "react";

import { usePowerUser } from "./preferences.js";
import type { Calibration } from "../model/types.js";

/** Row counts worth offering. The grid is log-spaced, so more rows buy
 *  resolution inside the Flood year rather than a longer flat tail. */
const SIZES = [400, 2000, 20000] as const;

interface Props {
  calibration: Calibration;
  /** Resolves the live source, booting it if necessary. */
  onDownload(points: number): Promise<string>;
  /** True when acting would start the 5.8 MB download. */
  willStartDownload: boolean;
  disabled?: boolean;
}

/** A name that says which model produced it, not just "series.csv". */
function filenameFor(calibration: Calibration, points: number): string {
  const { chronology, boundary } = calibration.request;
  const scenario = calibration.presetKey
    ? `${chronology}-${boundary}`
    : `${chronology}-${boundary}-custom`;
  return `card-${scenario}-${points}rows.csv`;
}

export function CsvDownload({
  calibration, onDownload, willStartDownload, disabled,
}: Props) {
  const powerUser = usePowerUser();
  const [points, setPoints] = useState<number>(2000);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const run = useCallback(async () => {
    setBusy(true);
    setError(null);
    try {
      const text = await onDownload(points);
      // A blob rather than a data: URI — 20,000 rows is ~1.5 MB, past what
      // some browsers accept in a URL.
      const url = URL.createObjectURL(
        new Blob([text], { type: "text/csv;charset=utf-8" }),
      );
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = filenameFor(calibration, points);
      anchor.click();
      // Revoking immediately can cancel the download in some browsers; one
      // turn of the event loop is enough for the click to have been taken.
      setTimeout(() => URL.revokeObjectURL(url), 0);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
    } finally {
      setBusy(false);
    }
  }, [onDownload, points, calibration]);

  return (
    <section className="panel" aria-labelledby="csv-heading">
      <h2 id="csv-heading">Download</h2>

      {error ? (
        <p className="notice" role="alert" style={{ marginTop: 0 }}>
          <strong>Could not build the file.</strong>{" "}
          <span className="converter-error">{error}</span>
        </p>
      ) : null}

      {!powerUser && willStartDownload ? (
        <p className="notice" style={{ marginTop: 0 }}>
          The file is written by the model itself, so this needs the full
          model — a <strong>5.8&nbsp;MB download</strong>, once.
        </p>
      ) : null}

      <label className="field">
        <span>Rows</span>
        <select
          value={points}
          disabled={disabled || busy}
          onChange={(e) => setPoints(Number(e.target.value))}
        >
          {SIZES.map((n) => (
            <option key={n} value={n}>{n.toLocaleString()}</option>
          ))}
        </select>
      </label>

      <button className="action" onClick={() => void run()} disabled={disabled || busy}>
        {busy ? "Preparing…" : "Download CSV"}
      </button>

      {powerUser ? null : (
        <p className="param-help" style={{ marginTop: ".6rem" }}>
          Ages, dates, λ at formation and the acceleration ratio, with a header
          recording the chronology, every parameter and each constraint&rsquo;s
          residual. Identical to what <code>card series</code> writes.
        </p>
      )}
    </section>
  );
}
