/**
 * The CARDulator mark.
 *
 * The same stylised λ(t) as `public/favicon.svg` — flat at background, a hard
 * jump at the Flood, an exponential relaxation after it — but drawn in
 * `currentColor` so the banner follows the theme, where the favicon cannot.
 *
 * Stylised on purpose: the real curve falls from 4.5e9 to 3.2e5 inside the
 * Flood year, which on a linear axis is a spike and then nothing. This is a
 * mark, not a figure, and the two should not be confused — every actual plot
 * in the app is generated by the model.
 */

/** Flat run, jump, then the decay. Shared by both renderings. */
const CURVE =
  "M 10 48 L 24 48 L 24 14 L 25.23 18.49 L 26.46 22.38 L 27.69 25.76 " +
  "L 28.92 28.7 L 30.15 31.25 L 31.38 33.46 L 32.62 35.38 L 33.85 37.04 " +
  "L 35.08 38.49 L 36.31 39.74 L 37.54 40.83 L 38.77 41.78 L 40 42.6 " +
  "L 41.23 43.31 L 42.46 43.93 L 43.69 44.47 L 44.92 44.93 L 46.15 45.34 " +
  "L 47.38 45.69 L 48.62 46 L 49.85 46.26 L 51.08 46.49 L 52.31 46.69 " +
  "L 53.54 46.86 L 54.77 47.01 L 56 47.14";

export function Logo({ size = 30 }: { size?: number }) {
  return (
    <svg
      className="logo"
      width={size}
      height={size}
      viewBox="0 0 64 64"
      aria-hidden="true"
      focusable="false"
    >
      <path d={`${CURVE} L 56 48 Z`} fill="currentColor" fillOpacity={0.16} />
      <path
        d={CURVE}
        fill="none"
        stroke="currentColor"
        strokeWidth={6}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
