#!/usr/bin/env python3
"""
Emit the first-paint layer: every preset, solved and sampled, as one JSON file.

This is what a first-time visitor sees while Pyodide is still downloading —
which, at 5.84 MB, can be 40 seconds on a slow connection.  It is a real code
path, not scaffolding, and it is generated by the same `card` package the live
source will run, so the two cannot disagree about what a preset means.

Run from anywhere:

    python web/tools/generate_precomputed.py            # -> web/public/precomputed.json
    python web/tools/generate_precomputed.py --check    # fail if the file is stale

`--check` is for CI: it regenerates into memory and compares, so a change to
the model or to presets.json that nobody re-ran shows up as a failed build
rather than as a stale chart in production.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

HERE = Path(__file__).resolve().parent
WEB = HERE.parent
REPO = WEB.parent

# Import `card` from the repo checkout when it is not pip-installed, so the
# generator works in a fresh clone without an editable install.
if str(REPO / "src") not in sys.path:
    sys.path.insert(0, str(REPO / "src"))

from card import __version__ as CARD_VERSION  # noqa: E402
from card.calibrate import solve_flood_only  # noqa: E402
from card.chronology import Chronology  # noqa: E402
from card.models import GeneralModel  # noqa: E402

PRESETS_PATH = WEB / "presets" / "presets.json"
ICS_PATH = WEB / "data" / "ics-units.json"
OUTPUT_PATH = WEB / "public" / "precomputed.json"

# Enough significant digits that rounding is far below the interpolation error
# the grid itself carries, while keeping the file small.
SIGFIGS = 9


def _round(value: float) -> float:
    """Round to SIGFIGS, and to a plain int when that is exact — JSON is smaller."""
    if value == 0.0:
        return 0.0
    rounded = float(f"%.{SIGFIGS}g" % value)
    return int(rounded) if rounded.is_integer() and abs(rounded) < 1e15 else rounded


def _true_age_grid(chronology: Chronology, model: GeneralModel,
                   anchors: List[float], points: int) -> List[float]:
    """
    Log-spaced true ages, with the points that must be exact unioned in.

    Two kinds of point have to be on the grid or the chart lies:

      * the model's breakpoints, as AGEs, so the kink at the Flood has a vertex
        instead of being rounded off by the two grid points either side;
      * each constraint's age, so the calibration anchors are exact rows rather
        than interpolated ones.

    Note what is deliberately *not* here: a pair of points straddling each
    breakpoint.  lambda(t) genuinely jumps there, but `forward_age` is the
    integral of a bounded rate, so it is continuous in true age — the curve has
    a kink, not a step.  A straddling pair would add a duplicate row and no
    information.  (A future lambda(t) series does need one, because that curve
    really does step.)

    Values are rounded to output precision *before* deduplication, so the file
    can never contain two rows with the same true age — which would be a
    degenerate interval for the interpolator to land in.
    """
    present = chronology.present_date
    lo, hi = 1.0, present

    ratio = (hi / lo) ** (1.0 / (points - 1))
    candidates = [lo * ratio ** i for i in range(points)]
    candidates.extend((0.0, present))
    candidates.extend(chronology.date_to_age(d) for d in model.breakpoints())
    candidates.extend(anchors)

    rounded = {_round(a) for a in candidates if 0.0 <= a <= present}
    return sorted(rounded)


#: Relative offset placing a sample just past a discontinuity.  Two competing
#: pressures: it must exceed the resolution of SIGFIGS rounding or the pair
#: collapses into a duplicate row (which happened, silently, to an earlier
#: attempt), and it must be small against 1/k_F or the sample records a lambda
#: that has already relaxed.  k_F reaches ~2/yr in this configuration, so 1e-6
#: cost 0.35% of the peak; 1e-7 costs 0.035% and still survives rounding.
_STEP_EPSILON = 1e-7


def _lambda_grid(chronology: Chronology, model: GeneralModel,
                 points: int) -> List[float]:
    """
    DATEs at which to sample lambda(t), linear plus the discontinuities.

    lambda genuinely steps at t_c, t_F and t_F2 — unlike `forward_age`, which
    is the integral of a bounded rate and therefore continuous.  So this grid
    *does* need a point either side of each breakpoint, and the age grid
    deliberately does not.  Without the pair, a chart renders the Flood as a
    diagonal ramp rather than a jump.

    `lambda_func` uses `<=`, so the sample at a breakpoint belongs to the
    earlier region and its partner must sit just after.

    The linear part alone is not enough.  Calibrating the Flood as an
    instantaneous onset drives k_F to ~2/yr, so lambda relaxes within about
    five years — while a 400-point linear grid over six millennia samples every
    fifteen.  The whole decay fell between two samples and the curve rendered
    as a bare spike.  So the relaxation regions are additionally sampled
    log-spaced in time-since-the-breakpoint, which resolves the shape for any
    k_F rather than for the one that happened to be in front of us.
    """
    present = chronology.present_date
    step = present / (points - 1)
    candidates = [i * step for i in range(points)]
    candidates.extend((0.0, present))
    for date in model.breakpoints():
        if 0.0 <= date <= present:
            candidates.append(date)
            after = date * (1.0 + _STEP_EPSILON) if date > 0.0 else _STEP_EPSILON
            if after <= present:
                candidates.append(after)
            # Resolve the relaxation that starts here, log-spaced so the shape
            # is captured whatever the decay constant turns out to be.
            span = present - date
            if span > 0:
                lo = max(1e-4, span * 1e-9)
                steps = 120
                ratio = (span / lo) ** (1.0 / (steps - 1))
                candidates.extend(date + lo * ratio ** i for i in range(steps))

    grid = sorted({_round(d) for d in candidates if 0.0 <= d <= present})

    # Fail loudly rather than shipping a chart that draws a ramp: if rounding
    # merged a breakpoint with its partner, the step is gone and nothing
    # downstream would notice.
    for date in model.breakpoints():
        if not 0.0 < date < present:
            continue
        rounded = _round(date)
        after = _round(date * (1.0 + _STEP_EPSILON))
        if rounded == after:
            raise ValueError(
                f"the straddle around breakpoint {date!r} collapsed under "
                f"{SIGFIGS}-significant-figure rounding; increase SIGFIGS or "
                "_STEP_EPSILON."
            )
        if rounded not in grid or after not in grid:
            raise ValueError(
                f"breakpoint {date!r} lost its straddling pair in the grid."
            )
    return grid


def _geologic_column(model: GeneralModel, chronology: Chronology,
                     units: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Each chronostratigraphic unit's secular span, as a young-earth duration.

    Computed here rather than in the browser because the precomputed layer
    cannot do it.  A duration is the *difference* of two inverse ages, and the
    older units differ in the fourth or fifth significant figure: interpolating
    at ~0.03% would put 13.7% error on the Silurian.  Exact in Python, shipped
    as numbers, is both correct and smaller than the data it replaces.

    A unit whose base is older than this calibration can produce is reported
    with `in_range: false` rather than dropped, so the chart can say that the
    column runs out rather than silently ending early.
    """
    present = chronology.present_date
    max_secular = model.max_secular_age(present)

    rows: List[Dict[str, Any]] = []
    younger_secular = 0.0
    younger_true = 0.0
    for unit in units:
        base_secular = float(unit["base_secular_age"])
        row: Dict[str, Any] = {
            "name": unit["name"],
            "rank": unit["rank"],
            "base_secular_age": base_secular,
            "top_secular_age": younger_secular,
        }
        if base_secular <= max_secular:
            base_true = model.inverse_age(base_secular, present)
            duration = base_true - younger_true
            secular_duration = base_secular - younger_secular
            row.update({
                "in_range": True,
                "base_true_age": _round(base_true),
                "top_true_age": _round(younger_true),
                "duration_true": _round(duration),
                # How much faster the clock ran: secular years elapsed per
                # young-earth year across this unit.
                "acceleration": _round(secular_duration / duration)
                if duration > 0 else None,
            })
            younger_true = base_true
        else:
            row["in_range"] = False
        younger_secular = base_secular
        rows.append(row)
    return rows


def build(presets: Dict[str, Any]) -> Dict[str, Any]:
    chronologies = presets["chronologies"]
    boundaries = presets["terminal_boundaries"]
    start_boundary = presets["flood_start_boundary"]
    flood_years = float(presets["flood_duration_years"])
    points = int(presets["series"]["points"])
    lambda_points = int(presets["series"].get("lambda_points", 400))
    ics = json.loads(ICS_PATH.read_text())
    units = ics["units"]

    out_chronologies: Dict[str, Any] = {}
    out_presets: Dict[str, Any] = {}

    for chron_key, chron_spec in chronologies.items():
        # t_F == t_F2: the acceleration is instantaneous and relaxes as a
        # single exponential. The Flood's depositional span is separate, and
        # only sets where the second constraint sits on that decay curve.
        flood_start = float(chron_spec["flood_start_date"])
        chronology = Chronology(
            age_of_earth=float(chron_spec["age_of_earth"]),
            flood_start_date=flood_start,
            flood_end_date=flood_start,
            ice_age_end_date=float(chron_spec["ice_age_end_date"]),
        )
        out_chronologies[chron_key] = {
            "label": chron_spec["label"],
            "provisional": bool(chron_spec.get("provisional", False)),
            **chronology.to_dict(),
            "flood_start_age": chronology.flood_start_age,
            "flood_deposition_end_age": chronology.flood_start_age - flood_years,
            "ice_age_end_age": chronology.ice_age_end_age,
        }

        for bound_key, bound_spec in boundaries.items():
            # The two pairs are the Flood's two stratigraphic contacts: its
            # onset, and the instant a year later when deposition ceased.
            flood_age = chronology.flood_start_age
            second_age = flood_age - flood_years

            result = solve_flood_only(
                flood_age=flood_age,
                flood_secular_age=float(start_boundary["secular_age"]),
                second_age=second_age,
                second_secular_age=float(bound_spec["secular_age"]),
                chronology=chronology,
                # Confining the acceleration to an instant forces a fast
                # relaxation: k_F lands near 2 here, past the default bracket.
                k_F_bracket=(1e-6, 1e3),
            )
            model = result.model
            present = chronology.present_date

            # The grid is already at output precision, so evaluate the model at
            # exactly the values that get written.  Rounding the input and the
            # output independently would store a pair that the model never
            # actually produced.
            grid = _true_age_grid(chronology, model, [flood_age, second_age], points)
            secular = [model.forward_age(age, present) for age in grid]
            lambda_grid = _lambda_grid(chronology, model, lambda_points)

            out_presets[f"{chron_key}:{bound_key}"] = {
                "chronology": chron_key,
                "boundary": bound_key,
                "label": f"{chron_spec['label']} — Flood ends at {bound_spec['label']}",
                "mode": "flood_only",
                "params": {
                    "lambda_c": model.lambda_c, "lambda_F": _round(model.lambda_F),
                    "lambda_bg": model.lambda_bg,
                    "k_c": model.k_c, "k_F": _round(model.k_F),
                    "t_c": model.t_c, "t_F": model.t_F, "t_F2": model.t_F2,
                },
                "residuals": [_round(r) for r in result.residuals],
                "max_abs_residual": _round(result.max_abs_residual),
                "max_secular_age": _round(model.max_secular_age(present)),
                "constraints": [
                    {"label": f"Flood begins — {start_boundary['label']}",
                     "true_age": flood_age,
                     "secular_age": float(start_boundary["secular_age"]),
                     "uncertainty": float(start_boundary["uncertainty"])},
                    {"label": f"Flood ends — {bound_spec['label']}",
                     "true_age": second_age,
                     "secular_age": float(bound_spec["secular_age"]),
                     "uncertainty": float(bound_spec["uncertainty"])},
                ],
                # Not a constraint any more: with acceleration confined to the
                # Flood, this is what the model *predicts* for the Ice Age.
                "ice_age_prediction": {
                    "true_age": chronology.ice_age_end_age,
                    "secular_age": _round(
                        model.forward_age(chronology.ice_age_end_age, present)),
                },
                "series": {
                    "true_age": grid,  # already rounded, already deduplicated
                    "secular_age": [_round(s) for s in secular],
                },
                # lambda(t) against DATE — the one curve whose x axis is a DATE
                # rather than an AGE, and the one that genuinely steps.
                "lambda_history": {
                    "date": lambda_grid,
                    "lambda": [_round(model.lambda_func(d)) for d in lambda_grid],
                },
                "geologic_column": _geologic_column(model, chronology, units),
            }

    return {
        "$comment": (
            "GENERATED by web/tools/generate_precomputed.py — do not edit. "
            "Regenerate after changing presets.json or the model."
        ),
        # Deliberately no git SHA. It would have to change on every commit,
        # which makes `--check` fail the moment the file is committed; and a
        # self-reported commit string goes stale the first time someone edits
        # the model without regenerating. `git log web/public/precomputed.json`
        # is both accurate and always current. `card_version` stays, because it
        # is what actually determines the numbers.
        "generator": {
            "card_version": CARD_VERSION,
            "series_points": points,
            "lambda_points": lambda_points,
        },
        "defaults": presets["defaults"],
        "boundaries": {k: {"label": v["label"],
                           "secular_age": float(v["secular_age"]),
                           "uncertainty": float(v["uncertainty"])}
                       for k, v in boundaries.items()},
        "flood_start_boundary": {"label": start_boundary["label"],
                                 "secular_age": float(start_boundary["secular_age"]),
                                 "uncertainty": float(start_boundary["uncertainty"])},
        "flood_duration_years": flood_years,
        "ics": {"version": ics["source"]["version"],
                "url": ics["source"]["url"],
                "reviewed": bool(ics["source"].get("reviewed", False))},
        "chronologies": out_chronologies,
        "presets": out_presets,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed output is stale")
    args = parser.parse_args()

    presets = json.loads(PRESETS_PATH.read_text())
    payload = build(presets)
    text = json.dumps(payload, separators=(",", ":")) + "\n"

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} does not exist; run this script.", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text() != text:
            print(f"{OUTPUT_PATH} is stale; re-run "
                  "`python web/tools/generate_precomputed.py`.", file=sys.stderr)
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO)} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text)

    n_presets = len(payload["presets"])
    size_kb = len(text.encode()) / 1024
    print(f"wrote {OUTPUT_PATH.relative_to(REPO)}: "
          f"{n_presets} presets, {size_kb:.0f} kB (card {CARD_VERSION})")
    for key, preset in payload["presets"].items():
        print(f"  {key:24s} lambda_F={preset['params']['lambda_F']:<12.6g} "
              f"k_F={preset['params']['k_F']:<12.6g} "
              f"max|res|={preset['max_abs_residual']:.1e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
