#!/usr/bin/env python3
"""
Emit the first-paint layer: every preset, solved and sampled, as one JSON file.

This is what a first-time visitor sees while Pyodide is still downloading —
which, at 5.84 MB, can be 40 seconds on a slow connection.  It is a real code
path, not scaffolding, and it is generated by the same `card` package the live
source will run, so the two cannot disagree about what a preset means.

Run from anywhere:

    python web/tools/generate_precomputed.py            # -> web/public/precomputed.json
    python web/tools/generate_precomputed.py --check    # fail if the file is stale

`--check` is for CI: it regenerates into memory and compares, so a change to
the model or to presets.json that nobody re-ran shows up as a failed build
rather than as a stale chart in production.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

HERE = Path(__file__).resolve().parent
WEB = HERE.parent
REPO = WEB.parent

# Import `card` from the repo checkout when it is not pip-installed, so the
# generator works in a fresh clone without an editable install.
if str(REPO / "src") not in sys.path:
    sys.path.insert(0, str(REPO / "src"))

from card import __version__ as CARD_VERSION  # noqa: E402
from card.calibrate import solve_flood_only  # noqa: E402
from card.chronology import Chronology  # noqa: E402
from card.models import GeneralModel  # noqa: E402

PRESETS_PATH = WEB / "presets" / "presets.json"
OUTPUT_PATH = WEB / "public" / "precomputed.json"

# Enough significant digits that rounding is far below the interpolation error
# the grid itself carries, while keeping the file small.
SIGFIGS = 9


def _round(value: float) -> float:
    """Round to SIGFIGS, and to a plain int when that is exact — JSON is smaller."""
    if value == 0.0:
        return 0.0
    rounded = float(f"%.{SIGFIGS}g" % value)
    return int(rounded) if rounded.is_integer() and abs(rounded) < 1e15 else rounded


def _true_age_grid(chronology: Chronology, model: GeneralModel,
                   anchors: List[float], points: int) -> List[float]:
    """
    Log-spaced true ages, with the points that must be exact unioned in.

    Two kinds of point have to be on the grid or the chart lies:

      * the model's breakpoints, as AGEs, so the kink at the Flood has a vertex
        instead of being rounded off by the two grid points either side;
      * each constraint's age, so the calibration anchors are exact rows rather
        than interpolated ones.

    Note what is deliberately *not* here: a pair of points straddling each
    breakpoint.  lambda(t) genuinely jumps there, but `forward_age` is the
    integral of a bounded rate, so it is continuous in true age — the curve has
    a kink, not a step.  A straddling pair would add a duplicate row and no
    information.  (A future lambda(t) series does need one, because that curve
    really does step.)

    Values are rounded to output precision *before* deduplication, so the file
    can never contain two rows with the same true age — which would be a
    degenerate interval for the interpolator to land in.
    """
    present = chronology.present_date
    lo, hi = 1.0, present

    ratio = (hi / lo) ** (1.0 / (points - 1))
    candidates = [lo * ratio ** i for i in range(points)]
    candidates.extend((0.0, present))
    candidates.extend(chronology.date_to_age(d) for d in model.breakpoints())
    candidates.extend(anchors)

    rounded = {_round(a) for a in candidates if 0.0 <= a <= present}
    return sorted(rounded)


def build(presets: Dict[str, Any]) -> Dict[str, Any]:
    chronologies = presets["chronologies"]
    boundaries = presets["boundaries"]
    second = presets["second_constraint"]
    points = int(presets["series"]["points"])

    out_chronologies: Dict[str, Any] = {}
    out_presets: Dict[str, Any] = {}

    for chron_key, chron_spec in chronologies.items():
        chronology = Chronology(
            age_of_earth=float(chron_spec["age_of_earth"]),
            flood_start_date=float(chron_spec["flood_start_date"]),
            flood_end_date=float(chron_spec["flood_end_date"]),
            ice_age_end_date=float(chron_spec["ice_age_end_date"]),
        )
        out_chronologies[chron_key] = {
            "label": chron_spec["label"],
            "provisional": bool(chron_spec.get("provisional", False)),
            **chronology.to_dict(),
            "flood_start_age": chronology.flood_start_age,
            "ice_age_end_age": chronology.ice_age_end_age,
        }

        for bound_key, bound_spec in boundaries.items():
            flood_age = chronology.flood_start_age
            second_age = chronology.ice_age_end_age

            result = solve_flood_only(
                flood_age=flood_age,
                flood_secular_age=float(bound_spec["secular_age"]),
                second_age=second_age,
                second_secular_age=float(second["secular_age"]),
                chronology=chronology,
            )
            model = result.model
            present = chronology.present_date

            # The grid is already at output precision, so evaluate the model at
            # exactly the values that get written.  Rounding the input and the
            # output independently would store a pair that the model never
            # actually produced.
            grid = _true_age_grid(chronology, model, [flood_age, second_age], points)
            secular = [model.forward_age(age, present) for age in grid]

            out_presets[f"{chron_key}:{bound_key}"] = {
                "chronology": chron_key,
                "boundary": bound_key,
                "label": f"{chron_spec['label']} / {bound_spec['label']}",
                "mode": "flood_only",
                "params": {
                    "lambda_c": model.lambda_c, "lambda_F": _round(model.lambda_F),
                    "lambda_bg": model.lambda_bg,
                    "k_c": model.k_c, "k_F": _round(model.k_F),
                    "k_PF": _round(model.k_PF),
                    "t_c": model.t_c, "t_F": model.t_F, "t_F2": model.t_F2,
                },
                "residuals": [_round(r) for r in result.residuals],
                "max_abs_residual": _round(result.max_abs_residual),
                "max_secular_age": _round(model.max_secular_age(present)),
                "constraints": [
                    {"label": bound_spec["label"], "true_age": flood_age,
                     "secular_age": float(bound_spec["secular_age"]),
                     "uncertainty": float(bound_spec["uncertainty"])},
                    {"label": second["label"], "true_age": second_age,
                     "secular_age": float(second["secular_age"]),
                     "uncertainty": float(second["uncertainty"])},
                ],
                "series": {
                    "true_age": grid,  # already rounded, already deduplicated
                    "secular_age": [_round(s) for s in secular],
                },
            }

    return {
        "$comment": (
            "GENERATED by web/tools/generate_precomputed.py — do not edit. "
            "Regenerate after changing presets.json or the model."
        ),
        # Deliberately no git SHA. It would have to change on every commit,
        # which makes `--check` fail the moment the file is committed; and a
        # self-reported commit string goes stale the first time someone edits
        # the model without regenerating. `git log web/public/precomputed.json`
        # is both accurate and always current. `card_version` stays, because it
        # is what actually determines the numbers.
        "generator": {
            "card_version": CARD_VERSION,
            "series_points": points,
        },
        "defaults": presets["defaults"],
        "boundaries": {k: {"label": v["label"],
                           "secular_age": float(v["secular_age"]),
                           "uncertainty": float(v["uncertainty"])}
                       for k, v in boundaries.items()},
        "second_constraint": {"label": second["label"],
                              "secular_age": float(second["secular_age"]),
                              "uncertainty": float(second["uncertainty"])},
        "chronologies": out_chronologies,
        "presets": out_presets,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed output is stale")
    args = parser.parse_args()

    presets = json.loads(PRESETS_PATH.read_text())
    payload = build(presets)
    text = json.dumps(payload, separators=(",", ":")) + "\n"

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} does not exist; run this script.", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text() != text:
            print(f"{OUTPUT_PATH} is stale; re-run "
                  "`python web/tools/generate_precomputed.py`.", file=sys.stderr)
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO)} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text)

    n_presets = len(payload["presets"])
    size_kb = len(text.encode()) / 1024
    print(f"wrote {OUTPUT_PATH.relative_to(REPO)}: "
          f"{n_presets} presets, {size_kb:.0f} kB (card {CARD_VERSION})")
    for key, preset in payload["presets"].items():
        print(f"  {key:24s} lambda_F={preset['params']['lambda_F']:<12.6g} "
              f"k_PF={preset['params']['k_PF']:<12.6g} "
              f"max|res|={preset['max_abs_residual']:.1e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
