#!/usr/bin/env python3
"""
Emit the first-paint layer: every preset, solved and sampled, as one JSON file.

This is what a first-time visitor sees while Pyodide is still downloading —
which, at 5.84 MB, can be 40 seconds on a slow connection.  It is a real code
path, not scaffolding, and it is generated by the same `card` package the live
source will run, so the two cannot disagree about what a preset means.

Run from anywhere:

    python web/tools/generate_precomputed.py            # -> web/public/precomputed.json
    python web/tools/generate_precomputed.py --check    # fail if the file is stale

`--check` is for CI: it regenerates into memory and compares, so a change to
the model or to presets.json that nobody re-ran shows up as a failed build
rather than as a stale chart in production.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any, Dict, List

HERE = Path(__file__).resolve().parent
WEB = HERE.parent
REPO = WEB.parent

# Import `card` from the repo checkout when it is not pip-installed, so the
# generator works in a fresh clone without an editable install.
if str(REPO / "src") not in sys.path:
    sys.path.insert(0, str(REPO / "src"))

from card import __version__ as CARD_VERSION  # noqa: E402
from card.calibrate import solve_flood_rate  # noqa: E402
from card.chronology import Chronology  # noqa: E402
from card.models import GeneralModel, GeneralModelParams  # noqa: E402
from card.parameters import (  # noqa: E402
    parameter_specs,
    split_fixed_and_free,
    to_json_schema,
)

PRESETS_PATH = WEB / "presets" / "presets.json"
ICS_PATH = WEB / "data" / "ics-units.json"
OUTPUT_PATH = WEB / "public" / "precomputed.json"
#: One file per preset, holding only the arrays the charts plot.
PRESET_DIR = WEB / "public" / "presets"

# Enough significant digits that rounding is far below the interpolation error
# the grid itself carries, while keeping the file small.
SIGFIGS = 9

# The series arrays dominate the file, and interpolating them is only good to
# ~0.3%, so storing nine significant figures spends bytes on digits nobody can
# use.  Seven is still three orders of magnitude finer than the interpolation.
SERIES_SIGFIGS = 7


def _round(value: float, sigfigs: int = SIGFIGS) -> float:
    """Round to `sigfigs`, and to a plain int when exact — JSON is smaller."""
    if value == 0.0:
        return 0.0
    rounded = float(f"%.{sigfigs}g" % value)
    return int(rounded) if rounded.is_integer() and abs(rounded) < 1e15 else rounded


def _relaxation_span(model: GeneralModel) -> float:
    """
    Years over which the post-Flood rate is still meaningfully above background.

    Derived from the model rather than assumed, because the two relaxation
    constants differ by three orders of magnitude: k_F reaches ~10/yr inside the
    Flood year, k_PF ~0.005/yr for millennia after.  A hardcoded window would be
    far too wide for one and far too narrow for the other.

    Sized from **both** rates, taking whichever needs the wider window.

    This used to read `k_F` alone, which covered the fast in-Flood drop and
    missed the post-Flood tail; the age grid's worst interpolation error sat at
    0.77% because of it.  That was tolerable while the presets were four curves
    of similar shape.  Adding the Ice Age offsets made it not: a 350-year offset
    forces k_PF an order of magnitude higher than the default, the tail it has
    to resolve is correspondingly shorter and steeper, and the worst error
    reached 4.2% -- against a UI that promises about 1%.
    """
    spans = []
    for rate_attr, amplitude in (("k_F", "lambda_F"), ("k_PF", "lambda_F2")):
        k = getattr(model, rate_attr, 0.0) or getattr(model.params, rate_attr, 0.0)
        excess = (getattr(model, amplitude, None)
                  or getattr(model.params, amplitude, 1.0)) - 1.0
        if k > 0.0 and excess > 0.0:
            # Where the excess has fallen to a millionth of background, with
            # margin.
            spans.append(1.5 * math.log(excess * 1e6) / k)
    return max(spans) if spans else float("inf")


def _true_age_grid(chronology: Chronology, model: GeneralModel,
                   anchors: List[float], points: int) -> List[float]:
    """
    Log-spaced true ages, with the points that must be exact unioned in.

    Two kinds of point have to be on the grid or the chart lies:

      * the model's breakpoints, as AGEs, so the kink at the Flood has a vertex
        instead of being rounded off by the two grid points either side;
      * each constraint's age, so the calibration anchors are exact rows rather
        than interpolated ones.

    Note what is deliberately *not* here: a pair of points straddling each
    breakpoint.  lambda(t) genuinely jumps there, but `forward_age` is the
    integral of a bounded rate, so it is continuous in true age — the curve has
    a kink, not a step.  A straddling pair would add a duplicate row and no
    information.  (A future lambda(t) series does need one, because that curve
    really does step.)

    Values are rounded to output precision *before* deduplication, so the file
    can never contain two rows with the same true age — which would be a
    degenerate interval for the interpolator to land in.
    """
    present = chronology.present_date
    lo, hi = 1.0, present

    ratio = (hi / lo) ** (1.0 / (points - 1))
    candidates = [lo * ratio ** i for i in range(points)]
    candidates.extend((0.0, present))
    candidates.extend(chronology.date_to_age(d) for d in model.breakpoints())
    candidates.extend(anchors)

    # The log grid is uniform in true age, but the curve is not: just younger
    # than a breakpoint, `forward_age` climbs by the whole post-relaxation
    # integral.  With k_F ~ 10 that is orders of magnitude between two
    # neighbouring samples, and interpolating across it is meaninglessly wrong
    # -- measured at 12,000% before this.  Refine log-spaced in time-since-the-breakpoint, the
    # same way the lambda grid does, so the climb is resolved for any k_F.
    settle = _relaxation_span(model)
    for date in model.breakpoints():
        age = chronology.date_to_age(date)
        if not 0.0 < age <= present:
            continue
        # Only as far as the rate is still moving.  Spreading the refinement
        # over the whole timeline wastes most of it on the flat tail, where the
        # base log grid is already exact; confining it to the relaxation gets
        # the same resolution for a third of the points.
        span = min(age, settle)
        lo_d = max(1e-4, span * 1e-9)
        steps = 500
        r = (span / lo_d) ** (1.0 / (steps - 1))
        candidates.extend(age - lo_d * r ** i for i in range(steps))

    rounded = {_round(a) for a in candidates if 0.0 <= a <= present}
    return sorted(rounded)


#: Relative offset placing a sample just past a discontinuity.  Two competing
#: pressures: it must exceed the resolution of SIGFIGS rounding or the pair
#: collapses into a duplicate row (which happened, silently, to an earlier
#: attempt), and it must be small against 1/k_F or the sample records a lambda
#: that has already relaxed.  k_F reaches ~10/yr in this configuration, so 1e-6
#: cost ~1.7% of the peak; 1e-7 costs ~0.17% and still survives rounding.
_STEP_EPSILON = 1e-7


def _lambda_grid(chronology: Chronology, model: GeneralModel,
                 points: int) -> List[float]:
    """
    DATEs at which to sample lambda(t), linear plus the discontinuities.

    lambda genuinely steps at t_c, t_F and t_F2 — unlike `forward_age`, which
    is the integral of a bounded rate and therefore continuous.  So this grid
    *does* need a point either side of each breakpoint, and the age grid
    deliberately does not.  Without the pair, a chart renders the Flood as a
    diagonal ramp rather than a jump.

    `lambda_func` uses `<=`, so the sample at a breakpoint belongs to the
    earlier region and its partner must sit just after.

    The linear part alone is not enough.  k_F reaches ~10/yr, so the in-Flood
    drop is spent inside the Flood year — while a 400-point linear grid over six
    millennia samples every fifteen years.  The whole drop fell between two
    samples and the curve rendered as a bare spike.  So the relaxation regions
    are additionally sampled log-spaced in time-since-the-breakpoint, which
    resolves the shape for any decay constant rather than for the one that
    happened to be in front of us.
    """
    present = chronology.present_date
    step = present / (points - 1)
    candidates = [i * step for i in range(points)]
    candidates.extend((0.0, present))
    for date in model.breakpoints():
        if 0.0 <= date <= present:
            candidates.append(date)
            after = date * (1.0 + _STEP_EPSILON) if date > 0.0 else _STEP_EPSILON
            if after <= present:
                candidates.append(after)
            # Resolve the relaxation that starts here, log-spaced so the shape
            # is captured whatever the decay constant turns out to be.
            span = present - date
            if span > 0:
                lo = max(1e-4, span * 1e-9)
                steps = 120
                ratio = (span / lo) ** (1.0 / (steps - 1))
                candidates.extend(date + lo * ratio ** i for i in range(steps))

    grid = sorted({_round(d) for d in candidates if 0.0 <= d <= present})

    # Fail loudly rather than shipping a chart that draws a ramp: if rounding
    # merged a breakpoint with its partner, the step is gone and nothing
    # downstream would notice.
    for date in model.breakpoints():
        if not 0.0 < date < present:
            continue
        rounded = _round(date)
        after = _round(date * (1.0 + _STEP_EPSILON))
        if rounded == after:
            raise ValueError(
                f"the straddle around breakpoint {date!r} collapsed under "
                f"{SIGFIGS}-significant-figure rounding; increase SIGFIGS or "
                "_STEP_EPSILON."
            )
        if rounded not in grid or after not in grid:
            raise ValueError(
                f"breakpoint {date!r} lost its straddling pair in the grid."
            )
    return grid


def _geologic_column(model: GeneralModel, chronology: Chronology,
                     units: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Each chronostratigraphic unit's secular span, as a young-earth duration.

    Computed here rather than in the browser because the precomputed layer
    cannot do it.  A duration is the *difference* of two inverse ages, and the
    older units differ in the fourth or fifth significant figure: interpolating
    at ~0.03% would put 13.7% error on the Silurian.  Exact in Python, shipped
    as numbers, is both correct and smaller than the data it replaces.

    A unit whose base is older than this calibration can produce is reported
    with `in_range: false` rather than dropped, so the chart can say that the
    column runs out rather than silently ending early.
    """
    present = chronology.present_date
    max_secular = model.max_secular_age(present)

    rows: List[Dict[str, Any]] = []
    younger_secular = 0.0
    younger_true = 0.0
    for unit in units:
        base_secular = float(unit["base_secular_age"])
        row: Dict[str, Any] = {
            "name": unit["name"],
            "rank": unit["rank"],
            "base_secular_age": base_secular,
            "top_secular_age": younger_secular,
        }
        if base_secular <= max_secular:
            base_true = model.inverse_age(base_secular, present)
            duration = base_true - younger_true
            secular_duration = base_secular - younger_secular
            row.update({
                "in_range": True,
                "base_true_age": _round(base_true),
                "top_true_age": _round(younger_true),
                "duration_true": _round(duration),
                # How much faster the clock ran: secular years elapsed per
                # young-earth year across this unit.
                "acceleration": _round(secular_duration / duration)
                if duration > 0 else None,
            })
            younger_true = base_true
        else:
            row["in_range"] = False
        younger_secular = base_secular
        rows.append(row)
    return rows


def _mode_schemas(presets: Dict[str, Any],
                  chronologies: Dict[str, Chronology]) -> Dict[str, Any]:
    """
    The parameter form, per mode and per chronology, from the package itself.

    The live source can answer this at runtime (`bridge.schema`), but only once
    Pyodide has booted -- and it deliberately does not boot until a reader asks
    for something the presets cannot answer.  Without the schema up front the
    parameter panel would have nothing to draw until after a 5.8 MB download,
    which is precisely backwards: the controls are what tell a reader the
    download is worth starting.

    So the same `to_json_schema` call runs here too.  Nothing is transcribed;
    adding a parameter to `GeneralModelParams` still makes a control appear with
    no frontend change, which is the property the whole approach exists for.
    Date bounds vary with the chronology, so there is one schema per pair.
    """
    specs = parameter_specs(GeneralModelParams)
    out: Dict[str, Any] = {}
    for mode_key, mode in presets["modes"].items():
        per_chronology: Dict[str, Any] = {}
        for chron_key, chronology in chronologies.items():
            # Chronology *names* resolve the way run configs let them, so a mode
            # can say `t_F: flood_start_date` and stay correct across
            # chronologies rather than hardcoding a date.
            resolved = {
                name: (float(getattr(chronology, value))
                       if isinstance(value, str) else float(value))
                for name, value in mode["fixed"].items()
            }
            free, pinned = split_fixed_and_free(GeneralModelParams, resolved)
            per_chronology[chron_key] = {
                "schema": to_json_schema(GeneralModelParams,
                                         chronology=chronology),
                # Order matters: this is the order controls are rendered in, and
                # it is the dataclass's own declaration order.
                "free": list(free),
                "fixed": {name: resolved[name] for name in pinned},
            }
        out[mode_key] = {
            "label": mode["label"],
            "enabled": bool(mode.get("enabled", False)),
            "by_chronology": per_chronology,
        }
    # `is_fittable` is false exactly when minimum == maximum (lambda_bg), so a
    # UI skips it structurally rather than by a hardcoded exclusion.
    out["$fittable"] = [n for n, s in specs.items() if s.is_fittable]
    return out


def build(presets: Dict[str, Any]) -> Dict[str, Any]:
    chronologies = presets["chronologies"]
    boundaries = presets["post_flood_boundaries"]
    calib = presets["calibration"]
    flood_years = float(presets["flood_duration_years"])
    points = int(presets["series"]["points"])
    lambda_points = int(presets["series"].get("lambda_points", 400))
    ics = json.loads(ICS_PATH.read_text())
    units = ics["units"]

    out_chronologies: Dict[str, Any] = {}
    out_presets: Dict[str, Any] = {}
    # Kept so the schemas can be built against the same objects the presets
    # were solved with, rather than reconstructed from the emitted dicts.
    built_chronologies: Dict[str, Chronology] = {}
    ice_offsets = presets["ice_age_offsets"]
    out_offsets: Dict[str, Any] = {}

    for chron_key, chron_spec in chronologies.items():
        # t_F == t_F2: the acceleration is instantaneous and relaxes as a
        # single exponential.
        # The Flood now has a real length, because lambda relaxes across it at
        # k_F.  solve_flood_rate treats that length as an input, so the
        # chronology has to carry it rather than collapsing t_F2 onto t_F.
        flood_start = float(chron_spec["flood_start_date"])
        chronology = Chronology(
            age_of_earth=float(chron_spec["age_of_earth"]),
            flood_start_date=flood_start,
            flood_end_date=float(chron_spec["flood_end_date"]),
            ice_age_end_date=float(chron_spec["ice_age_end_date"]),
        )
        built_chronologies[chron_key] = chronology
        out_chronologies[chron_key] = {
            "label": chron_spec["label"],
            "provisional": bool(chron_spec.get("provisional", False)),
            **chronology.to_dict(),
            "flood_start_age": chronology.flood_start_age,
            "post_flood_boundary_age": chronology.flood_start_age - flood_years,
            "ice_age_end_age": chronology.ice_age_end_age,
        }

        # Each Ice Age offset is a *different chronology*: solve_flood_rate
        # reads the Ice Age AGE from the chronology it is handed, so moving the
        # date means handing it another one rather than passing a stray number.
        own_offset = chronology.ice_age_end_date - chronology.flood_end_date
        offset_specs = [("default", own_offset, "chronology default")]
        offset_specs += [(f"y{int(n)}", float(n), None)
                         for n in ice_offsets["years_after_flood"]]

        for offset_key, offset_years, offset_note in offset_specs:
          ice_chronology = Chronology(
              age_of_earth=chronology.age_of_earth,
              flood_start_date=chronology.flood_start_date,
              flood_end_date=chronology.flood_end_date,
              ice_age_end_date=chronology.flood_end_date + offset_years,
          )
          out_offsets.setdefault(offset_key, {
              "label": (f"{offset_years:,.0f} yr after the Flood"
                        + (f" ({offset_note})" if offset_note else "")),
              "years_after_flood": {},
          })["years_after_flood"][chron_key] = offset_years

          for bound_key, bound_spec in boundaries.items():
              # Three matched pairs: the Flood's onset at the pre-Flood contact,
              # its end one year later at the selected post-Flood contact, and
              # the end of the Ice Age well into the relaxation.  All three AGEs
              # come from the chronology -- solve_flood_rate reads them there, so
              # passing anything else would silently solve a different problem.
              flood_age = ice_chronology.flood_start_age
              second_age = ice_chronology.flood_end_age
              ice_age = ice_chronology.ice_age_end_age

              result = solve_flood_rate(
                  pre_flood_secular_age=float(calib["flood_start"]["secular_age"]),
                  post_flood_secular_age=float(bound_spec["secular_age"]),
                  ice_age_secular_age=float(calib["ice_age_end"]["secular_age"]),
                  chronology=ice_chronology,
              )
              model = result.model
              present = ice_chronology.present_date

              # The grid is already at output precision, so evaluate the model at
              # exactly the values that get written.  Rounding the input and the
              # output independently would store a pair that the model never
              # actually produced.
              grid = _true_age_grid(ice_chronology, model,
                                    [flood_age, second_age, ice_age], points)
              secular = [model.forward_age(age, present) for age in grid]
              lambda_grid = _lambda_grid(ice_chronology, model, lambda_points)

              out_presets[f"{chron_key}:{bound_key}:{offset_key}"] = {
                  "chronology": chron_key,
                  "boundary": bound_key,
                    "ice_age": offset_key,
                  "label": f"{chron_spec['label']} — Flood ends at {bound_spec['label']}",
                  "mode": "flood_only",
                  "params": {
                      "lambda_c": model.lambda_c, "lambda_F": _round(model.lambda_F),
                      "lambda_bg": model.lambda_bg,
                      "k_c": model.k_c, "k_F": _round(model.k_F),
                      "k_PF": _round(model.k_PF),
                      "t_c": model.t_c, "t_F": model.t_F, "t_F2": model.t_F2,
                  },
                  "residuals": [_round(r) for r in result.residuals],
                  "max_abs_residual": _round(result.max_abs_residual),
                  "max_secular_age": _round(model.max_secular_age(present)),
                  "constraints": [
                      {"label": f"Flood begins — {calib['flood_start']['label']}",
                       "true_age": flood_age,
                       "secular_age": float(calib["flood_start"]["secular_age"]),
                       "uncertainty": float(calib["flood_start"]["uncertainty"])},
                      {"label": f"Flood ends — {bound_spec['label']}",
                       "true_age": second_age,
                       "secular_age": float(bound_spec["secular_age"]),
                       "uncertainty": float(bound_spec["uncertainty"])},
                      # The third pair.  It was a prediction while one k had to
                      # serve both phases; k_PF is what makes it an anchor, and
                      # `residuals` has always carried three entries, so omitting
                      # it here left the list and the residuals disagreeing.
                      {"label": calib["ice_age_end"]["label"],
                       "true_age": ice_age,
                       "secular_age": float(calib["ice_age_end"]["secular_age"]),
                       "uncertainty": float(calib["ice_age_end"]["uncertainty"])},
                  ],
                  # The handover value: what the in-Flood exponential has fallen
                  # to by t_F2, and therefore where the post-Flood one starts.
                  # Not a free parameter -- continuity pins it -- but worth
                  # emitting, because it is the number that shows how much of the
                  # drop happens inside the Flood year.
                  "lambda_F2": _round(model.params.lambda_F2),
                  "series": {
                      "true_age": grid,  # already rounded, already deduplicated
                      "secular_age": [_round(s, SERIES_SIGFIGS) for s in secular],
                  },
                  # lambda(t) against DATE — the one curve whose x axis is a DATE
                  # rather than an AGE, and the one that genuinely steps.
                  "lambda_history": {
                      "date": lambda_grid,
                      "lambda": [_round(model.lambda_func(d), SERIES_SIGFIGS)
                                 for d in lambda_grid],
                  },
                  "geologic_column": _geologic_column(model, ice_chronology, units),
              }

    return {
        "$comment": (
            "GENERATED by web/tools/generate_precomputed.py — do not edit. "
            "Regenerate after changing presets.json or the model."
        ),
        # Deliberately no git SHA. It would have to change on every commit,
        # which makes `--check` fail the moment the file is committed; and a
        # self-reported commit string goes stale the first time someone edits
        # the model without regenerating. `git log web/public/precomputed.json`
        # is both accurate and always current. `card_version` stays, because it
        # is what actually determines the numbers.
        "generator": {
            "card_version": CARD_VERSION,
            "series_points": points,
            "lambda_points": lambda_points,
        },
        "defaults": {**presets["defaults"], "ice_age": ice_offsets["default"]},
        "boundaries": {k: {"label": v["label"],
                           "secular_age": float(v["secular_age"]),
                           "uncertainty": float(v["uncertainty"])}
                       for k, v in boundaries.items()},
        # Both fixed pairs. The third — the post-Flood contact — varies per
        # preset and lives under `boundaries`.
        "calibration": {
            # `uncertainty` travels with the pair: the live source builds its
            # own Constraint objects from this catalogue, and without it the
            # two sources describe the same fit differently.
            key: {"label": spec["label"],
                  "secular_age": float(spec["secular_age"]),
                  "uncertainty": float(spec["uncertainty"])}
            for key, spec in calib.items()
        },
        "ice_age_offsets": {
            "default": ice_offsets["default"],
            "options": out_offsets,
        },
        "flood_duration_years": flood_years,
        "ics": {"version": ics["source"]["version"],
                "url": ics["source"]["url"],
                "reviewed": bool(ics["source"].get("reviewed", False)),
                # The unit list is the same for every preset -- it is the ICS
                # chart, not a result -- so it belongs here rather than being
                # dug out of whichever preset's column happens to be loaded.
                "units": [{"name": u["name"], "rank": u["rank"],
                           "base_secular_age": float(u["base_secular_age"])}
                          for u in units]},
        "chronologies": out_chronologies,
        "modes": _mode_schemas(presets, built_chronologies),
        "presets": out_presets,
    }


#: What the charts plot, and the only part that is large. Everything else --
#: params, constraints, residuals, labels -- stays in the index, because
#: `supports()` and the preset picker need it before anything is chosen.
BODY_KEYS = ("series", "lambda_history", "geologic_column")


def _body_stem(key: str) -> str:
    """`masoretic:kpg:default` -> `masoretic-kpg-default`, safe in a URL."""
    return key.replace(":", "-")


def _body_path(key: str):
    return PRESET_DIR / f"{_body_stem(key)}.json"


def _body_text(body: Dict[str, Any]) -> str:
    return json.dumps(body, separators=(",", ":")) + "\n"


def _split(payload: Dict[str, Any]):
    """
    Separate the index from the per-preset arrays.

    Seventy presets carry 3.8 MB of curve between them, and `main.tsx` awaits
    this file before the first paint -- shipping it whole would trade the very
    thing the precomputed layer exists to provide. The index keeps every
    preset's metadata so the picker and `supports()` still work offline, and
    the arrays are fetched when a preset is actually chosen.
    """
    bodies: Dict[str, Any] = {}
    index = dict(payload)
    index["presets"] = {}
    for key, preset in payload["presets"].items():
        bodies[key] = {k: preset[k] for k in BODY_KEYS}
        index["presets"][key] = {k: v for k, v in preset.items()
                                 if k not in BODY_KEYS}
    return index, bodies


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed output is stale")
    args = parser.parse_args()

    presets = json.loads(PRESETS_PATH.read_text())
    payload = build(presets)
    index, bodies = _split(payload)
    text = json.dumps(index, separators=(",", ":")) + "\n"

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} does not exist; run this script.", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text() != text:
            print(f"{OUTPUT_PATH} is stale; re-run "
                  "`python web/tools/generate_precomputed.py`.", file=sys.stderr)
            return 1
        stale = [k for k, body in bodies.items()
                 if not _body_path(k).exists()
                 or _body_path(k).read_text() != _body_text(body)]
        if stale:
            print(f"{len(stale)} preset file(s) stale, e.g. {stale[0]}; re-run "
                  "`python web/tools/generate_precomputed.py`.", file=sys.stderr)
            return 1
        orphans = sorted(f.name for f in PRESET_DIR.glob("*.json")
                         if f.stem not in {_body_stem(k) for k in bodies})
        if orphans:
            print(f"stale preset file(s) with no preset: {', '.join(orphans)}",
                  file=sys.stderr)
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO)} and {len(bodies)} preset "
              "files are up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text)

    # Rewritten from scratch, so a renamed or removed preset cannot leave a
    # file behind that the index no longer lists.
    if PRESET_DIR.exists():
        for old_file in PRESET_DIR.glob("*.json"):
            old_file.unlink()
    PRESET_DIR.mkdir(parents=True, exist_ok=True)
    body_bytes = 0
    for key, body in bodies.items():
        blob = _body_text(body)
        _body_path(key).write_text(blob)
        body_bytes += len(blob.encode())

    n_presets = len(payload["presets"])
    size_kb = len(text.encode()) / 1024
    print(f"wrote {OUTPUT_PATH.relative_to(REPO)}: index for {n_presets} "
          f"presets, {size_kb:.0f} kB (card {CARD_VERSION})")
    print(f"wrote {len(bodies)} files to {PRESET_DIR.relative_to(REPO)}/: "
          f"{body_bytes/1024:.0f} kB total, "
          f"{body_bytes/len(bodies)/1024:.0f} kB each")
    for key, preset in payload["presets"].items():
        print(f"  {key:24s} lambda_F={preset['params']['lambda_F']:<12.6g} "
              f"k_PF={preset['params']['k_PF']:<12.6g} "
              f"max|res|={preset['max_abs_residual']:.1e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
