/**
 * The seam between the UI and wherever the model actually runs.
 *
 * Two implementations answer this interface: `PrecomputedSource`, reading a
 * static table generated by `card` in CI, and `PyodideSource`, calling `card`
 * for real in a Web Worker. The UI never knows which is answering.
 *
 * Every method is async even where one implementation could answer
 * synchronously. That is deliberate and load-bearing: the live source is
 * genuinely across a worker boundary, and retrofitting sync-to-async through a
 * component tree later is miserable. Async from the start costs nothing.
 *
 * Scalar operations take a `Calibration` rather than a `CalibrationRequest` so
 * they do not re-solve. Solving is ~6-8 ms; evaluating the model is
 * microseconds, and a dragged slider does many evaluations per solve.
 */

import type {
  Calibration,
  CalibrationRequest,
  LambdaSeries,
  Series,
} from "./types.js";

export type SourceKind = "precomputed" | "live";

export interface ModelSource {
  readonly kind: SourceKind;

  /**
   * True when this source computes rather than interpolates.
   *
   * The UI should render inexact scalars with a "≈" and avoid quoting more
   * digits than the interpolation supports.
   */
  readonly exact: boolean;

  /**
   * Whether this source can answer at all.
   *
   * `PrecomputedSource` returns false for anything with custom parameters:
   * it holds six solved presets and cannot solve a seventh. The caller's
   * response is to `ensureLive()` and wait, not to retry.
   */
  supports(request: CalibrationRequest): boolean;

  /** Solve, or look up a solved preset. Rejects `UnsupportedRequestError`. */
  calibrate(request: CalibrationRequest): Promise<Calibration>;

  /**
   * Sample the calibrated curve.
   *
   * `points` is a hint. The precomputed source ignores it and returns the grid
   * it has, because resampling interpolated data at higher density would
   * manufacture precision it does not possess.
   */
  series(calibration: Calibration, points?: number): Promise<Series>;

  /**
   * Sample lambda against DATE — the decay-rate history.
   *
   * Separate from `series` because it is a different curve on a different
   * axis: DATE rather than AGE, and genuinely discontinuous where the age
   * curve only has a kink.
   */
  lambdaHistory(calibration: Calibration, points?: number): Promise<LambdaSeries>;

  /** Apparent secular age for a true age. Both AGEs. */
  forwardAge(calibration: Calibration, trueAge: number): Promise<number>;

  /** True age that would appear as `secularAge`. Both AGEs. */
  inverseAge(calibration: Calibration, secularAge: number): Promise<number>;

  /** Release anything held (worker, interpreter). Idempotent. */
  dispose?(): Promise<void>;
}
